### ISSUE TITLE
[Bug] Message 'remove' not understood

### ISSUE THREAD

**Issue by okhick** [scztt/Deferred.quark#1]
```
^^ ERROR: Message 'remove' not understood.
Perhaps you misspelled 'resume', or meant to call 'remove' on another receiver?
```
You've mentioned elsewhere that you may have fixed this but it looks like the error still persists for me when using the Quark from this repo. I think it has to do with reassigning `waitingThreads` on line 196 with the results of the `remove` method--which is the removed value not the Array. If we just call `remove` and not reassign it looks like it fixes the issue. Something like this:

``` sc
prWait {
	|timeout|
	if (resolved == \unresolved) {
		waitingThreads = waitingThreads.add(thisThread.threadPlayer);

		// ... removed for brevity

		waitingThreads.remove(thisThread.threadPlayer);
	}
}
```
Happy to put up a PR if it makes it easier for you!

**Comment by scztt** [comment]
Fixed. I noticed this some time ago but hadn't pushed the change, good catch!
